### ISSUE TITLE
11.02.2023

### ISSUE THREAD

**Issue by ksn4376** [nikitastupin/prodcal_ics#14]
Здравствуйте!
Почему в вашем календаре 11.02.2023 рабочий день?

**Comment by nuklea** [comment]
https://hh.ru/calendar -- есть выходной
https://prodcal.nikitastupin.com/prodcal.ics -- нет выходного

**Comment by nikitastupin** [comment]
Изменения в #15 должны решить проблему. Возможно, потребуется некоторое время, чтобы файл .ics обновился. Если проблема повторится, можете заново открыть эту задачу или открыть новую! Спасибо!
